import { ThemeProvider } from "@/components/layouts/themeProvider";
import { AppProvider } from "@/context";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   adjustFontFallback: false,
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <ThemeProvider attribute="class">
            <NextTopLoader color="#2299DD" />
            {children}
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
